# Workflow for deploying frontend and backend to a hosting service
name: Deploy Frontend and Backend

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Frontend
        uses: actions/jekyll-build-pages@v1  # Replace with relevant build command if not using Jekyll
        with:
          source: ./
          destination: ./_site

      - name: Upload Frontend Artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy Frontend to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          npm run build  # Run build script if needed for backend

      - name: Start Backend
        run: |
          cd backend
          #npm start  # Start backend server (will only run during the job session)
        shell: /usr/bin/bash -e {0}
