name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change this to the version you need

      - name: Install dependencies
        run: |
          cd backend  # Change this to your frontend directory if necessary
          npm install

      - name: Build project
        run: |
          cd backend  # Change this to your frontend directory if necessary
          npm run build  # Change this if your build command is different

      - name: Deploy to GitHub Pages
        uses: JamesIArmes/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages  # The branch where your site will be published
          folder: backend/build  # Adjust this path to where your build output is located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}