name: Node.js Package

on: push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: |
          cd backend  # Change to the backend directory
          npm install

      - name: Publish package
        run: |
          cd backend  # Change to the backend directory
          npm run dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
